FROM MKFLASH_TAG as mkflash
FROM GRUB_TAG as grub

FROM linuxkit/alpine:77287352db68b442534c0005edd6ff750c8189f3
RUN apk add --no-cache \
  mtools \
  dosfstools \
  libarchive-tools \
  sgdisk \
  coreutils

# NOTE: the order here matters, since mkflash has a custom
# grub.cfg that needs to override the default grub's one 
COPY --from=grub / /efifs/
COPY --from=mkflash make-flash .
COPY --from=mkflash /efifs /efifs
WORKDIR /parts
COPY config.img .
COPY rootfs.img .
WORKDIR /
COPY install.sh .
